import { VCFundConfig } from "@/lib/types";

export const vcFundsConfig: VCFundConfig[] = [
  {
    id: "peakxv",
    name: "PeakXV Partners",
    logoPath: "/logos/vc/peakxv.png",
    jobsBoardBaseUrl: "https://careers.peakxv.com",
    platform: "consider",
    color: "#1a1a2e",
    logoDark: true,
  },
  {
    id: "accel",
    name: "Accel",
    logoPath: "/logos/vc/accel.png",
    jobsBoardBaseUrl: "https://jobs.accel.com",
    platform: "getro",
    color: "#4f46e5",
  },
  {
    id: "lightspeed",
    name: "Lightspeed",
    logoPath: "/logos/vc/lightspeed.svg",
    jobsBoardBaseUrl: "https://jobs.lsvp.com",
    platform: "consider",
    color: "#dc2626",
  },
  {
    id: "nexus",
    name: "Nexus Venture Partners",
    logoPath: "/logos/vc/nexus.png",
    jobsBoardBaseUrl: "https://jobs.nexusvp.com",
    platform: "consider",
    color: "#0891b2",
  },
  {
    id: "gc",
    name: "General Catalyst",
    logoPath: "/logos/vc/gc.png",
    jobsBoardBaseUrl: "https://jobs.generalcatalyst.com",
    platform: "getro",
    color: "#059669",
  },
  {
    id: "blume",
    name: "Blume Ventures",
    logoPath: "/logos/vc/blume.svg",
    jobsBoardBaseUrl: "https://jobs.blume.vc",
    platform: "getro",
    color: "#14305A",
    logoDark: true,
  },
  {
    id: "bessemer",
    name: "Bessemer Venture Partners",
    logoPath: "/logos/vc/bessemer.svg",
    jobsBoardBaseUrl: "https://jobs.bvp.com",
    platform: "consider",
    color: "#1B3A5C",
    logoDark: true,
  },
];
